let jokes = [
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don’t scientists trust atoms? Because they make up everything.",
  "I’m reading a book about anti-gravity. It’s impossible to put down!",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Parallel lines have so much in common. It’s a shame they’ll never meet.",
  "What do you call fake spaghetti? An impasta.",
  "I used to play piano by ear..., But now I use my hands.",
  "I asked the IT guy, “How do you make a motherboard?” He said, “I tell her about my job.”",
  "Why did the math book look sad? Because it had too many problems.",
  "I told my computer I needed a break, and now it won’t stop sending me Kit-Kat ads.",
  "Why do cows wear bells? Because their horns don’t work.",
  "I’m on a seafood diet. I see food and I eat it.",
  "Why did the coffee file a police report? It got mugged.",
  "I used to be addicted to the hokey pokey, but then I turned myself around.",
  "How does a penguin build its house? Igloos it together.",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "I would tell you a construction joke, but I’m still working on it.",
  "Why couldn’t the bicycle stand up by itself? It was two-tired.",
  "I’m no good at math, but I know that two wrongs don’t make a right—only a left.",
  "What did one hat say to the other? Stay here, I’m going on ahead.",
  "I only know 25 letters of the alphabet. I don’t know y.",
  "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "I told my friend 10 jokes to make him laugh. Sadly, no pun in ten did.",
  "What did the zero say to the eight? Nice belt!",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "Did you hear about the claustrophobic astronaut? He needed a little space.",
  "Why can’t your nose be 12 inches long? Because then it would be a foot.",
  "What do you call a can opener that doesn’t work? A can’t opener.",
  "I tried to catch fog yesterday. Mist.",
  "Why did the chicken go to the seance? To talk to the other side.",
  "I used to work in a shoe recycling shop. It was sole-destroying.",
  "What do you get from a pampered cow? Spoiled milk.",
  "Why was the stadium so cool? It was filled with fans.",
  "I accidentally swallowed some food coloring. The doctor says I’m okay, but I feel like I’ve dyed a little inside.",
  "Why do bees have sticky hair? Because they use honeycombs.",
  "How do you organize a space party? You planet.",
  "I told a joke about a roof once… It went over everyone’s head.",
  "Did you hear about the kidnapping at school? It’s fine, he woke up.",
  "I have a joke about time travel, but I’m not gonna share it. You guys didn’t like it.",
  "Why don’t oysters donate to charity? Because they’re shellfish.",
  "Why are skeletons so calm? Because nothing gets under their skin.",
  "Why are elevator jokes so classic and good? They work on many levels.",
  "What do you call a pile of cats? A meowtain.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "Why did the invisible man turn down the job offer? He couldn’t see himself doing it.",
  "Why did Cinderella get kicked off the soccer team? Because she always ran away from the ball.",
  "How does Moses make his coffee? Hebrews it.",
  "Why did the man get hit by a bike every day? He was stuck in a vicious cycle.",
  "Why did the cookie go to the hospital? Because it felt crummy.",
  "What did the fish say when it hit the wall? Dam.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
  "What do you call an alligator in a vest? An investigator.",
  "How do cows stay up to date with current events? They read the moos-paper.",
  "What does a nosy pepper do? Gets jalapeño business!",
  "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
  "How do you make holy water? You boil the hell out of it.",
  "Why was the computer cold? It left its Windows open.",
  "I tried writing with a broken pencil. It was pointless.",
  "Why did the man put his money in the freezer? He wanted cold hard cash.",
  "Why did the banker switch careers? He lost interest.",
  "Why did the photo go to jail? It was framed.",
  "I got hit in the head with a can of soda. Luckily, it was a soft drink.",
  "What happens to a frog’s car when it breaks down? It gets toad away.",
  "What’s orange and sounds like a parrot? A carrot.",
  "Why did the cow go to space? To see the moooon.",
  "What do you call two birds in love? Tweethearts.",
  "I tried to take a selfie with a squirrel. It was a little nuts.",
  "Why are ghosts bad at lying? Because you can see right through them.",
  "Why was the broom late? It swept in.",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the cat sit on the computer? To keep an eye on the mouse.",
  "Why don’t mountains get cold in the winter? They wear snowcaps.",
  "How does a scientist freshen their breath? With experi-mints.",
  "Why did the belt get arrested? For holding up a pair of pants.",
  "Why did the grape stop in the middle of the road? It ran out of juice.",
  "Why did the tree go to the barber? It needed a trim.",
  "What do you call a sleeping bull? A bulldozer.",
  "What do you get when you cross a vampire and a snowman? Frostbite.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "Why did the banana go to the doctor? Because it wasn’t peeling well.",
  "How do you catch a squirrel? Climb a tree and act like a nut.",
  "Why did the man run around his bed? Because he was trying to catch up on sleep.",
  "How do you make a tissue dance? Put a little boogie in it.",
  "Why don’t some couples go to the gym? Because some relationships don’t work out.",
  "Why are pirates so bad at the alphabet? They always get stuck at 'C'.",
  "I told my suitcase no vacation this year. Now I’m dealing with emotional baggage.",
  "Why don’t you ever trust a ladder? It’s always up to something.",
  "Why was the belt arrested? For a waist of time.",
  "Why did the calendar get promoted? Because it had a lot of dates.",
  "Why did the scarecrow become a successful neurosurgeon? Outstanding in his field.",
  "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
  "How does a dog stop a video? It presses the paws button.",
  "How do you make an octopus laugh? With ten-tickles.",
  "Why did the barber win the race? Because he knew all the shortcuts.",
  "Why do melons have weddings? Because they cantaloupe.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "Why did the musician get kicked out of the band? He was always flat.",
  "Why can’t a nose be 12 inches long? Because then it’d be a foot.",
  "What did the traffic light say to the car? Don’t look, I’m changing.",
  "Why did the man sit on the clock? He wanted to be on time.",
  "What’s brown and sticky? A stick.",
  "What did the left eye say to the right eye? Between us, something smells."
];


const fetchJoke = () => {

  document.getElementById("insertJoke").innerHTML = "";
  let randomNumber = Math.floor(Math.random() * 100);

  document.getElementById("insertJoke").innerHTML = jokes[randomNumber];
  document.getElementById("insertJoke").classList.add("joke");

  readAloud(randomNumber);

}

const readAloud = (randomNumber) => {
  
  const msg = new SpeechSynthesisUtterance();
  msg.text = jokes[randomNumber];
  msg.lanf = "en-US";

  window.speechSynthesis.speak(msg);
}